export enum TipoSolucion {
  SILLA_SALVAESCALERAS_FLOW_X,
  SILLA_SALVAESCALERAS_CURVA_DOBLE_RAIL,
  SILLA_SALVAESCALERAS_HOMEGLIDE,
  SILLA_SALVAESCALERAS_HOMEGLIDE_EXTERIOR,
  SILLA_SALVAESCALERAS_SMART_AIR_CURVA,
  SILLA_SALVAESCALERAS_SMART_AIR_RECTA,
  PLATAFORMA_SUPRA_CURVA,
  PLATAFORMA_SUPRA_RECTA,
  PLATAFORMA_STARK_RECTA,
}
